Repository jenkinsci/file-operations-plugin, pull requests merged in 2024-08, with the labels that each got.

#119 Automated PR
  pom.xml
Labels: chore

#120 Automated PR
  pom.xml
Labels: dependencies

#121 Update README with pipeline usage examples and explanations for Copy, Delete, Create, Download Operations
  README.md
Labels: documentation
