Repository jenkinsci/file-operations-plugin, pull requests merged in 2024-07, with the labels that each got.

#106 Improve usage of targetLocation if renameFiles and flattenFiles is used
  src/main/java/sp/sd/fileoperations/FileCopyOperation.java
  src/main/resources/sp/sd/fileoperations/FileCopyOperation/help-renameFiles.html
  src/main/resources/sp/sd/fileoperations/FileCopyOperation/help-sourceCaptureExpression.html
  src/test/java/sp/sd/fileoperations/FileCopyOperationTest.java
Labels: bug

#105 Allow copy and delete of ant default exclude files
  pom.xml
  src/main/java/sp/sd/fileoperations/FileCopyOperation.java
  src/main/java/sp/sd/fileoperations/FileDeleteOperation.java
  src/main/java/sp/sd/fileoperations/FileTransformOperation.java
  src/main/java/sp/sd/fileoperations/dsl/FileOperationsJobDslContext.java
  src/test/java/sp/sd/fileoperations/FileCopyOperationTest.java
  src/test/java/sp/sd/fileoperations/FileDeleteOperationTest.java
  src/test/java/sp/sd/fileoperations/FileTransformOperationTest.java
Labels: enhancement

#109 Add Tests for FileJoinOperation
  src/test/java/sp/sd/fileoperations/FileJoinOperationTest.java
Labels: tests

#110 Add Tests for FolderCreateOperation
  src/test/java/sp/sd/fileoperations/FolderCreateOperationTest.java
Labels: tests

#111 Add Tests for FolderCopyOperation
  src/test/java/sp/sd/fileoperations/FolderCopyOperationTest.java
Labels: tests

#112 Add Tests for FolderDeleteOperation
  src/test/java/sp/sd/fileoperations/FolderDeleteOperationTest.java
Labels: tests

#113 Add Tests for FolderRenameOperation
  src/test/java/sp/sd/fileoperations/FolderRenameOperationTest.java
Labels: tests
