Repository jenkinsci/file-operations-plugin, pull requests merged in 2025-02, with the labels that each got.

#154 Bump bom to 4228.v0a_71308d905b_
  pom.xml
Labels: dependencies

#155 feat(java): Require Jenkins core 2.479.3 and Java 17.
  pom.xml
Labels: dependencies, developer

#156 Migrate to httpclient5
  pom.xml
  src/main/java/sp/sd/fileoperations/FileDownloadOperation.java
Labels: developer
